// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'





    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4X0xmuKl-XwvzqiTxPNvfI7-bWA2As10',
    appId: '1:112495846289:web:4dae3a80327743731f7030',
    messagingSenderId: '112495846289',
    projectId: 'flutter-application2-38cdd',
    authDomain: 'flutter-application2-38cdd.firebaseapp.com',
    storageBucket: 'flutter-application2-38cdd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_3lN9fQN5F6aaCeboXHNSRENMyymQ4Rg',
    appId: '1:112495846289:android:e1bb603d514431ec1f7030',
    messagingSenderId: '112495846289',
    projectId: 'flutter-application2-38cdd',
    storageBucket: 'flutter-application2-38cdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaq1sF2zgxaSf--nPMnEYpvniB4OTuF8',
    appId: '1:112495846289:ios:1043a929ef8128f51f7030',
    messagingSenderId: '112495846289',
    projectId: 'flutter-application2-38cdd',
    storageBucket: 'flutter-application2-38cdd.appspot.com',
    iosClientId: '112495846289-q6vus2tchnmf50v2chp1nslvodul08kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );



  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcaq1sF2zgxaSf--nPMnEYpvniB4OTuF8',
    appId: '1:112495846289:ios:1043a929ef8128f51f7030',
    messagingSenderId: '112495846289',
    projectId: 'flutter-application2-38cdd',
    storageBucket: 'flutter-application2-38cdd.appspot.com',
    iosClientId: '112495846289-q6vus2tchnmf50v2chp1nslvodul08kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

}